# Generated by Django 5.1.2 on 2024-10-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolte',
            name='date_recolte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reine',
            name='date_remplacement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
