# Generated by Django 5.1.2 on 2024-10-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0003_alter_reine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reine',
            name='id',
        ),
        migrations.AddField(
            model_name='reine',
            name='id_reine',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ruche',
            name='id_reine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reine', to='ruches.reine'),
            preserve_default=False,
        ),
    ]
