# Generated by Django 5.1.2 on 2024-10-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0004_remove_reine_id_reine_id_reine_ruche_id_reine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reine',
            name='rucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reine', to='ruches.rucher'),
        ),
    ]
