# Generated by Django 5.1.2 on 2024-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0005_alter_reine_rucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rucher',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
