# Generated by Django 5.1.2 on 2024-10-20 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0006_alter_rucher_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rucher',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
