# Generated by Django 5.1.2 on 2024-10-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0007_alter_rucher_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reine',
            name='sante',
            field=models.CharField(choices=[('Normale', 'Normale'), ('Infecter', 'Infecter')], max_length=100),
        ),
    ]
